id = "isnet@imgly-fp32"
family = "isnet"
algorithm_family = "isnet"
model_encoding = "fp32"
preprocessing_profile = "imgly-isnet"
file = "../projects/javascript/background-removal-js/bundle/models/isnet"
external = true
sha256 = "cc2c9f5c1751b9737cb81e708ff0c5e9542c2205daed22418a4fd2ab5d4c481a"
input_name = "input"
output_name = "output"
layout = "nchw"
width = 1024
height = 1024
aspect = "stretch"
resize_filter = "bilinear"
channel_order = "rgb"
scale = 1.0
mean = [128.0, 128.0, 128.0]
std = [256.0, 256.0, 256.0]
activation = "none"
output_normalization = "clamp"
source_url = "https://github.com/imgly/background-removal-js"
source_commit = "12f56cc4f2a90d624e165a715748d22efc7a1d93"
model_version = "bundle-model-isnet"
license_identifier = "MIT"
license_file = "../projects/javascript/background-removal-js/LICENSE.md"
license_sha256 = "5ffb8eaf206c79f334260d6373dc8deda5235901d14e0c34e9b77e4c82cecb87"
intended_use_approved = true
opset = 15
input_shape = [1, 3, 1024, 1024]
output_shape = [1, 1, 1024, 1024]
input_type = "f32"
output_type = "f32"
output_index = 0
