id = "u2net@rembg-v0.0.0"
family = "u2net"
algorithm_family = "u2net"
model_variant = "general"
model_domain = "general"
model_encoding = "fp32"
preprocessing_profile = "generic"
file = "../projects/python/rembg/u2net.onnx"
external = true
sha256 = "8d10d2f3bb75ae3b6d527c77944fc5e7dcd94b29809d47a739a7a728a912b491"
input_name = "input.1"
output_name = "1959"
layout = "nchw"
width = 320
height = 320
aspect = "stretch"
resize_filter = "lanczos3"
channel_order = "rgb"
scale = 1.0
mean = [0.485, 0.456, 0.406]
std = [0.229, 0.224, 0.225]
activation = "none"
output_normalization = "minmax"
source_url = "https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx"
source_commit = "030a9ed79dbfcf8c58a1dc15a8dca3ccd2355709"
model_version = "rembg-v0.0.0-u2net"
license_identifier = "MIT"
license_file = "../projects/python/rembg/LICENSE.txt"
license_sha256 = "90a3215072968fd304669c5389f04f1274a587abdd0507d99dead0f5511f8999"
intended_use_approved = true
opset = 11
input_shape = [1, 3, 320, 320]
output_shape = [1, 1, 320, 320]
input_type = "f32"
output_type = "f32"
output_index = 0
