id = "u2net@rembg-v0.0.0-cloth"
family = "u2net"
algorithm_family = "u2net"
model_variant = "cloth-seg"
model_domain = "cloth"
model_encoding = "fp32"
preprocessing_profile = "generic"
file = "../projects/python/rembg/u2net_cloth_seg.onnx"
external = true
sha256 = "6d2cbc27bfbdc989e1fd325656d65902ecc6a3ccbe94b2d3655ec114efcb128e"
input_name = "input"
output_name = "output"
layout = "nchw"
width = 768
height = 768
aspect = "stretch"
resize_filter = "lanczos3"
channel_order = "rgb"
scale = 1.0
mean = [0.485, 0.456, 0.406]
std = [0.229, 0.224, 0.225]
activation = "none"
output_normalization = "none"
source_url = "https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net_cloth_seg.onnx"
source_commit = "030a9ed79dbfcf8c58a1dc15a8dca3ccd2355709"
model_version = "rembg-v0.0.0-u2net-cloth-seg"
license_identifier = "MIT"
license_file = "../projects/python/rembg/LICENSE.txt"
license_sha256 = "90a3215072968fd304669c5389f04f1274a587abdd0507d99dead0f5511f8999"
intended_use_approved = true
opset = 11
input_shape = ["batch", 3, 768, 768]
output_shape = ["batch", 4, 768, 768]
input_type = "f32"
output_type = "f32"
output_index = 0
